language: bash

os: linux
dist: xenial

services:
- docker

before_install:
# 升级 Docker 最新 stable
- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version
# 升级最新 Docker Compose
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
# ubuntu 14.04
# - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
# - sudo service docker restart
# ubuntu 16.04
- sudo mkdir -p /etc/systemd/system/docker.service.d
- echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
- echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl daemon-reload
- sudo systemctl cat docker
- sudo systemctl restart docker

script:
  - cp .env.example .env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose build ${PHP_VERSION} --parallel
  - if [ -n "$UNIT" ];then docker build --target=php -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-unit-alpine ${FOLDER}/unit; fi
  - if [ -n "$SUPERVISORD" ];then docker build -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-supervisord-alpine ${FOLDER}/supervisord; fi
  - if [ -n "$COMPOSER" ];then docker build -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-composer-alpine ${FOLDER}/composer; fi
  - if [ -n "$SINGLE" ];then docker build -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-single-alpine ${FOLDER}/single; fi
  - if [ -n "$SWOOLE" ];then docker build -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-swoole-alpine ${FOLDER}/swoole; fi
  - if [ -n "$FPM" ];then docker build --target=php -t $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-fpm-alpine ${FOLDER}/alpine; fi

after_success:
  - if [ -n "$UNIT" ];then docker push $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-unit-alpine; fi
  - if [ -n "$SUPERVISORD" ];then docker push $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-supervisord-alpine; fi
  - if [ -n "$COMPOSER" ];then docker push $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-composer-alpine; fi
  - if [ -n "$SINGLE" ];then docker push $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-single-alpine; fi
  - if [ -n "$SWOOLE" ];then docker push $DOCKER_HUB_USERNAME/php:${PHP_TAG_VERSION}-swoole-alpine; fi
  - if [ -n "$FPM" ];then docker-compose push ${PHP_VERSION}; fi
  - bash tag.sh
  - curl -X POST https://hooks.microbadger.com/images/$DOCKER_HUB_USERNAME/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=

branches:
  only:
  - master
  - dev

env:
  matrix:
  # - PHP_VERSION=5_6_X FOLDER=5.6 PHP_TAG_VERSION=5.6.40 FPM=1
  # - PHP_VERSION=7_0_X FOLDER=7.0 PHP_TAG_VERSION=7.0.33 FPM=1
  - PHP_VERSION=7_1_X FOLDER=7.1 PHP_TAG_VERSION=7.1.26 FPM=1

  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 FPM=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 SWOOLE=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 UNIT=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 SUPERVISORD=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 COMPOSER=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.15 SINGLE=1

  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 FPM=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 SWOOLE=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 UNIT=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 SUPERVISORD=1
  - PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 COMPOSER=1

  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1

  global:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - DOCKER_BUILDKIT=1
  - DOCKER_CHANNEL=stable # test nightly
  - DOCKER_HUB_USERNAME=khs1994

matrix:
  fast_finish: true
  allow_failures:
  # - env: PHP_VERSION=7_3_X FOLDER=7.3 PHP_TAG_VERSION=7.3.2 FPM=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly FPM=1
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly SWOOLE=1
