version: "3.6"

services:

  7_3_X:
    build:
      context: ./7.3/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_73:-7.3.0}
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_73:-7.3.0}-fpm-alpine

  7_2_X:
    build:
      context: ./7.2/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_72:-7.2.7}
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_72:-7.2.7}-fpm-alpine

  7_1_X:
    build:
      context: ./7.1/alpine
      args:
        PHP_VERSION: ${PHP_VERSION_71:-7.1.19}
        # ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:${PHP_VERSION_71:-7.1.19}-fpm-alpine
